# Default values for myapp.# Default values for myapp.

# This is a YAML-formatted file.# This is a YAML-formatted file.

# Declare variables to be passed into your templates.# Declare variables to be passed into your templates.



# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

replicaCount: 1replicaCount: 1



# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/

image:image:

  repository: ghcr.io/swathi-velogoti/myapp  repository: myapp

  # This sets the pull policy for images.  # This sets the pull policy for images.

  pullPolicy: IfNotPresent  pullPolicy: IfNotPresent

  # Overrides the image tag whose default is the chart appVersion.  # Overrides the image tag whose default is the chart appVersion.

  tag: "latest"  tag: "latest"



# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

imagePullSecrets: []imagePullSecrets: []

# This is to override the chart name.# This is to override the chart name.

nameOverride: ""nameOverride: ""

fullnameOverride: ""fullnameOverride: ""



# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/

serviceAccount:serviceAccount:

  # Specifies whether a service account should be created.  # Specifies whether a service account should be created.

  create: true  create: true

  # Automatically mount a ServiceAccount's API credentials?  # Automatically mount a ServiceAccount's API credentials?

  automount: true  automount: true

  # Annotations to add to the service account.  # Annotations to add to the service account.

  annotations: {}  annotations: {}

  # The name of the service account to use.  # The name of the service account to use.

  # If not set and create is true, a name is generated using the fullname template.  # If not set and create is true, a name is generated using the fullname template.

  name: ""  name: ""



# This is for setting Kubernetes Annotations to a Pod.# This is for setting Kubernetes Annotations to a Pod.

# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

podAnnotations: {}podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.# This is for setting Kubernetes Labels to a Pod.

# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

podLabels: {}podLabels: {}



podSecurityContext: {}podSecurityContext: {}

  # fsGroup: 2000  # fsGroup: 2000



securityContext: {}securityContext: {}

  # capabilities:  # capabilities:

  #   drop:  #   drop:

  #   - ALL  #   - ALL

  # readOnlyRootFilesystem: true  # readOnlyRootFilesystem: true

  # runAsNonRoot: true  # runAsNonRoot: true

  # runAsUser: 1000  # runAsUser: 1000



# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/

service:service:

  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

  type: ClusterIP  type: ClusterIP

  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports

  port: 8080  port: 8080



# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/

ingress:ingress:

  enabled: true  enabled: true

  className: ""  className: ""

  annotations: {}  annotations: {}

    # kubernetes.io/ingress.class: nginx    # kubernetes.io/ingress.class: nginx

    # kubernetes.io/tls-acme: "true"    # kubernetes.io/tls-acme: "true"

  hosts:  hosts:

    - host: myapp.127.0.0.1.nip.io    - host: myapp.127.0.0.1.nip.io

      paths:      paths:

        - path: /        - path: /

          pathType: Prefix          pathType: Prefix

  tls: []  tls: []

    # - secretName: chart-example-tls

# -- Expose the service via gateway-api HTTPRoute    #   hosts:

# Requires Gateway API resources and suitable controller installed within the cluster    #     - chart-example.local

# (see: https://gateway-api.sigs.k8s.io/guides/)

httpRoute:# -- Expose the service via gateway-api HTTPRoute

  # HTTPRoute enabled.# Requires Gateway API resources and suitable controller installed within the cluster

  enabled: false# (see: https://gateway-api.sigs.k8s.io/guides/)

  # HTTPRoute annotations.httpRoute:

  annotations: {}  # HTTPRoute enabled.

  # Which Gateways this Route is attached to.  enabled: false

  parentRefs:  # HTTPRoute annotations.

  - name: gateway  annotations: {}

    sectionName: http  # Which Gateways this Route is attached to.

    # namespace: default  parentRefs:

  # Hostnames matching HTTP header.  - name: gateway

  hostnames:    sectionName: http

  - chart-example.local    # namespace: default

  # List of rules and filters applied.  # Hostnames matching HTTP header.

  rules:  hostnames:

  - matches:  - chart-example.local

    - path:  # List of rules and filters applied.

        type: PathPrefix  rules:

        value: /headers  - matches:

  #   filters:    - path:

  #   - type: RequestHeaderModifier        type: PathPrefix

  #     requestHeaderModifier:        value: /headers

  #       set:  #   filters:

  #       - name: My-Overwrite-Header  #   - type: RequestHeaderModifier

  #         value: this-is-the-only-value  #     requestHeaderModifier:

  #       remove:  #       set:

  #       - User-Agent  #       - name: My-Overwrite-Header

  # - matches:  #         value: this-is-the-only-value

  #   - path:  #       remove:

  #       type: PathPrefix  #       - User-Agent

  #       value: /echo  # - matches:

  #     headers:  #   - path:

  #     - name: version  #       type: PathPrefix

  #       value: v2  #       value: /echo

  #     headers:

resources: {}  #     - name: version

  # We usually recommend not to specify default resources and to leave this as a conscious  #       value: v2

  # choice for the user. This also increases chances charts run on environments with little

  # resources, such as Minikube. If you do want to specify resources, uncomment the followingresources: {}

  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.  # We usually recommend not to specify default resources and to leave this as a conscious

  # limits:  # choice for the user. This also increases chances charts run on environments with little

  #   cpu: 100m  # resources, such as Minikube. If you do want to specify resources, uncomment the following

  #   memory: 128Mi  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

  # requests:  # limits:

  #   cpu: 100m  #   cpu: 100m

  #   memory: 128Mi  #   memory: 128Mi

  # requests:

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/  #   cpu: 100m

livenessProbe:  #   memory: 128Mi

  httpGet:

    path: /health# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

    port: httplivenessProbe:

readinessProbe:  httpGet:

  httpGet:    path: /health

    path: /health    port: http

    port: httpreadinessProbe:

  httpGet:

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/    path: /health

autoscaling:    port: http

  enabled: false

  minReplicas: 1# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/

  maxReplicas: 100autoscaling:

  targetCPUUtilizationPercentage: 80  enabled: false

  # targetMemoryUtilizationPercentage: 80  minReplicas: 1

  maxReplicas: 100

# Additional volumes on the output Deployment definition.  targetCPUUtilizationPercentage: 80

volumes: []  # targetMemoryUtilizationPercentage: 80

  # - name: foo

  #   secret:# Additional volumes on the output Deployment definition.

  #     secretName: mysecretvolumes: []

  #     optional: false  # - name: foo

  #   secret:

# Additional volumeMounts on the output Deployment definition.  #     secretName: mysecret

volumeMounts: []  #     optional: false

  # - name: foo

  #   mountPath: "/etc/foo"# Additional volumeMounts on the output Deployment definition.

  #   readOnly: truevolumeMounts: []

  # - name: foo

nodeSelector: {}  #   mountPath: "/etc/foo"

  #   readOnly: true

tolerations: []

nodeSelector: {}

affinity: {}
tolerations: []

affinity: {}
